// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcjulnyrfwvhtaopovqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjanVsbnlyZnd2aHRhb3BvdnFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NjI5MjIsImV4cCI6MjA2MDEzODkyMn0.Gdfjpn-unmOp9HCvUowXRJf2GVlYFGW1SXVQYzK0sv4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);